language: python
python:
  - "3"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests

script:
  - coverage run -m --source=./pymc  pytest
after_success:
  - coveralls
